<a href="https://colab.research.google.com/github/Henrislim/machine-learning-projects/blob/main/wathch_reviews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Document Clustering and Topic Modeling 

**Brief Introduction**
In this project, we use unsupervised learning models to cluster unlabeled documents into different groups, visualize the results and identify their latent topics/structures.

Contents:

* Part 0: Set Environment
* Part 1: Load Data
* Part 2: Tokenizing and Stemming
* Part 3: TF-IDF
* Part 4: K-means clustering
* Part 5: Topic Modeling - Latent Dirichlet Allocation

# Part 0: Setup Google Drive Environment

In [1]:
!pip install -U -q PyDrive

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [2]:
#https://drive.google.com/file/d/1s99b5gaWmn-gxltLuMGifMy_sCzHtkjU/view?usp=sharing
file = drive.CreateFile({'id':'1s99b5gaWmn-gxltLuMGifMy_sCzHtkjU'}) # replace the id with id of file you want to access
file.GetContentFile('watch_reviews.tsv')  # tab-separated

# Part 1: Load Data

In [18]:
import numpy as np
import pandas as pd
import nltk
# import gensim

from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [19]:
# Load data into dataframe
df = pd.read_csv('watch_reviews.tsv', sep='\t', error_bad_lines=False)

b'Skipping line 8704: expected 15 fields, saw 22\nSkipping line 16933: expected 15 fields, saw 22\nSkipping line 23726: expected 15 fields, saw 22\n'
b'Skipping line 85637: expected 15 fields, saw 22\n'
b'Skipping line 132136: expected 15 fields, saw 22\nSkipping line 158070: expected 15 fields, saw 22\nSkipping line 166007: expected 15 fields, saw 22\nSkipping line 171877: expected 15 fields, saw 22\nSkipping line 177756: expected 15 fields, saw 22\nSkipping line 181773: expected 15 fields, saw 22\nSkipping line 191085: expected 15 fields, saw 22\nSkipping line 196273: expected 15 fields, saw 22\nSkipping line 196331: expected 15 fields, saw 22\n'
b'Skipping line 197000: expected 15 fields, saw 22\nSkipping line 197011: expected 15 fields, saw 22\nSkipping line 197432: expected 15 fields, saw 22\nSkipping line 208016: expected 15 fields, saw 22\nSkipping line 214110: expected 15 fields, saw 22\nSkipping line 244328: expected 15 fields, saw 22\nSkipping line 248519: expected 15 fields,

In [20]:
df.head()

marketplace  ...  review_date
0          US  ...   2015-08-31
1          US  ...   2015-08-31
2          US  ...   2015-08-31
3          US  ...   2015-08-31
4          US  ...   2015-08-31

[5 rows x 15 columns]

In [21]:
# Remove missing value
df.dropna(subset=['review_body'],inplace=True)
df.reset_index(inplace=True, drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960056 entries, 0 to 960055
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   marketplace        960056 non-null  object
 1   customer_id        960056 non-null  int64 
 2   review_id          960056 non-null  object
 3   product_id         960056 non-null  object
 4   product_parent     960056 non-null  int64 
 5   product_title      960054 non-null  object
 6   product_category   960056 non-null  object
 7   star_rating        960056 non-null  int64 
 8   helpful_votes      960056 non-null  int64 
 9   total_votes        960056 non-null  int64 
 10  vine               960056 non-null  object
 11  verified_purchase  960056 non-null  object
 12  review_headline    960049 non-null  object
 13  review_body        960056 non-null  object
 14  review_date        960052 non-null  object
dtypes: int64(5), object(10)
memory usage: 109.9+ MB


In [22]:
# use the first 10000 data as our training data
data = df.loc[:9999, 'review_body'].tolist()

# Part 2: Tokenizing and Stemming

Load stopwords and stemmer function from NLTK library.

Stop words are words like "a", "the", or "in" which don't convey significant meaning.

Stemming is the process of breaking a word down into its root.

In [23]:
# Use nltk's English stopwords.
stopwords = nltk.corpus.stopwords.words('english') #stopwords.append("n't")
stopwords.append("'s")
stopwords.append("'m")
stopwords.append("br") #html <br>
stopwords.append("watch")

print ("We use " + str(len(stopwords)) + " stop-words from nltk library.")
print (stopwords[:10])

We use 183 stop-words from nltk library.
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


In [24]:
# use our defined functions to analyze (i.e. tokenize, stem) our reviews.
from nltk.stem.snowball import SnowballStemmer
# from nltk.stem import WordNetLemmatizer 

stemmer = SnowballStemmer("english")

# tokenization and stemming
def tokenization_and_stemming(text):
    tokens = []
    # exclude stop words and tokenize the document, generate a list of string 
    for word in nltk.word_tokenize(text):
        if word.lower() not in stopwords:
            tokens.append(word.lower())

    filtered_tokens = []
    
    # filter out any tokens not containing letters (e.g., numeric tokens, raw punctuation)
    for token in tokens:
        if token.isalpha():
            filtered_tokens.append(token)
            
    # stemming
    stems = [stemmer.stem(t) for t in filtered_tokens]
    return stems

# Part 3: TF-IDF

TF: Term Frequency

IDF: Inverse Document Frequency

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
# define vectorizer parameters
# TfidfVectorizer will help us to create tf-idf matrix
# max_df : maximum document frequency for the given word
# min_df : minimum document frequency for the given word
# max_features: maximum number of words
# use_idf: if not true, we only calculate tf
# stop_words : built-in stop words
# tokenizer: how to tokenize the document
# ngram_range: (min_value, max_value), eg. (1, 3) means the result will include 1-gram, 2-gram, 3-gram
tfidf_model = TfidfVectorizer(max_df=0.99, max_features=3000,
                                 min_df=0.01, stop_words='english',
                                 use_idf=True, tokenizer=tokenization_and_stemming, ngram_range=(1,1))

tfidf_matrix = tfidf_model.fit_transform(data) #fit the vectorizer to synopses

print ("In total, there are " + str(tfidf_matrix.shape[0]) + \
      " reviews and " + str(tfidf_matrix.shape[1]) + " terms.")

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['afterward', 'alon', 'alreadi', 'alway', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becom', 'besid', 'cri', 'describ', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'forti', 'henc', 'hereaft', 'herebi', 'howev', 'hundr', 'inde', 'mani', 'meanwhil', 'moreov', 'nobodi', 'noon', 'noth', 'nowher', 'otherwis', 'perhap', 'pleas', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'thenc', 'thereaft', 'therebi', 'therefor', 'togeth', 'twelv', 'twenti', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In total, there are 10000 reviews and 222 terms.


In [26]:
#Save the terms identified by TF-IDF.
# words
tf_selected_words = tfidf_model.get_feature_names()
# print out words
tf_selected_words[0:10]

['abl',
 'absolut',
 'accur',
 'actual',
 'adjust',
 'alarm',
 'alreadi',
 'alway',
 'amaz',
 'amazon']

# Part 4: K-means clustering

In [27]:
# k-means clustering
from sklearn.cluster import KMeans

num_clusters = 5

# number of clusters
km = KMeans(n_clusters=num_clusters)
km.fit(tfidf_matrix)

clusters = km.labels_.tolist()

## 4.1. Analyze K-means Result

In [28]:
# create DataFrame films from all of the input files.
product = { 'review': df[:10000].review_body, 'cluster': clusters}
frame = pd.DataFrame(product, columns = ['review', 'cluster'])
frame.head(10)

review  cluster
0  Absolutely love this watch! Get compliments al...        1
1       I love this watch it keeps time wonderfully.        4
2                                          Scratches        1
3  It works well on me. However, I found cheaper ...        1
4  Beautiful watch face.  The band looks nice all...        1
5  i love this watch for my purpose, about the pe...        1
6  for my wife and she loved it, looks great and ...        0
7  I was about to buy this thinking it was a Swis...        1
8  Watch is perfect. Rugged with the metal &#34;B...        0
9  Great quality and build.<br />The motors are r...        1

In [29]:
print ("Number of reviews included in each cluster:")
frame['cluster'].value_counts().to_frame()

Number of reviews included in each cluster:


cluster
1     6899
0     1108
4      808
2      634
3      551

In [30]:
km.cluster_centers_

array([[0.00139959, 0.00384064, 0.00558391, ..., 0.00546538, 0.0088299 ,
        0.01227755],
       [0.00551117, 0.00577883, 0.00643945, ..., 0.00940257, 0.02506315,
        0.01667115],
       [0.        , 0.        , 0.00170727, ..., 0.00323498, 0.00411007,
        0.00166219],
       [0.        , 0.        , 0.00091413, ..., 0.00125781, 0.0075891 ,
        0.00094289],
       [0.00096511, 0.02076273, 0.00077358, ..., 0.00077296, 0.00555338,
        0.00513697]])

In [31]:
km.cluster_centers_.shape

(5, 222)

In [42]:
print ("<Document clustering result by K-means>")

#km.cluster_centers_ denotes the importances of each items in centroid.
#We need to sort it in decreasing-order and get the top k items.
order_centroids = km.cluster_centers_.argsort()[:, ::-1] 

Cluster_keywords_summary = {}
for i in range(num_clusters):
    print ("Cluster " + str(i) + " words:", end='')
    Cluster_keywords_summary[i] = []
    for ind in order_centroids[i, :6]: #replace 6 with n words per cluster
        Cluster_keywords_summary[i].append(tf_selected_words[ind])
        print (tf_selected_words[ind] + ",", end='')
    print ()
    
    cluster_reviews = frame[frame.cluster==i].review.tolist()
    print ("Cluster " + str(i) + " reviews (" + str(len(cluster_reviews)) + " reviews): ")
    print (", ".join(cluster_reviews[0:2]))
    print ()

<Document clustering result by K-means>
Cluster 0 words:great,look,price,work,product,love,
Cluster 0 reviews (1108 reviews): 
for my wife and she loved it, looks great and a great price!, Watch is perfect. Rugged with the metal &#34;Bull Bars&#34;. The red accents are a great touch and I get compliments when wearing it. If you are worried about being able to read this in sunlight or in the dark don't! The LED ilumination works great! I might even get this in a different color for my next G-Shock purchase!

Cluster 1 words:look,like,time,band,work,beauti,
Cluster 1 reviews (6899 reviews): 
Absolutely love this watch! Get compliments almost every time I wear it. Dainty., Scratches

Cluster 2 words:good,product,look,price,qualiti,recommend,
Cluster 2 reviews (634 reviews): 
very good, It's a good value, and a good functional watch strap.  It's super wide though, and takes more space on the wrist than I'd like.

Cluster 3 words:nice,look,price,realli,love,like,
Cluster 3 reviews (551 revi

# Part 5: Topic Modeling - Latent Dirichlet Allocation

In [33]:
# Use LDA for clustering
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=5)

In [34]:
# document topic matrix for tfidf_matrix_lda
lda_output = lda.fit_transform(tfidf_matrix)
print(lda_output.shape)
print(lda_output)

(10000, 5)
[[0.57273061 0.05979591 0.05965026 0.24828969 0.05953353]
 [0.65722717 0.08419718 0.08424481 0.08945636 0.08487448]
 [0.10000135 0.10000121 0.10000082 0.59999563 0.10000099]
 ...
 [0.09766847 0.04631896 0.04475911 0.76389291 0.04736054]
 [0.04366976 0.0438115  0.82388524 0.04445674 0.04417676]
 [0.05666558 0.05941871 0.05982127 0.76115293 0.0629415 ]]


In [35]:
# topics and words matrix
topic_word = lda.components_
print(topic_word.shape)
print(topic_word)

(5, 222)
[[  0.20087776  59.59132546   1.9366278  ...   3.51156401   0.38610753
    0.20188367]
 [  0.20132826   0.20049325   2.65783138 ...   0.20239222   0.20106425
    0.20119412]
 [  0.20748848   0.78846628   0.2050834  ...   1.53414392  76.44024485
    1.48364094]
 [ 30.00036313   1.11623363  41.65635907 ...  60.97577041  24.98144364
  132.19337114]
 [ 10.74207465   0.20333462   7.36798034 ...   9.06870199  92.95986846
    1.26172758]]


In [36]:
# column names
topic_names = ["Topic" + str(i) for i in range(lda.n_components)]

# index names
doc_names = ["Doc" + str(i) for i in range(len(data))]

df_document_topic = pd.DataFrame(np.round(lda_output, 2), columns=topic_names, index=doc_names)

# get dominant topic for each document
topic = np.argmax(df_document_topic.values, axis=1)
df_document_topic['topic'] = topic

df_document_topic.head(10)

Topic0  Topic1  Topic2  Topic3  Topic4  topic
Doc0    0.57    0.06    0.06    0.25    0.06      0
Doc1    0.66    0.08    0.08    0.09    0.08      0
Doc2    0.10    0.10    0.10    0.60    0.10      3
Doc3    0.06    0.07    0.06    0.74    0.06      3
Doc4    0.05    0.04    0.04    0.56    0.31      3
Doc5    0.70    0.07    0.08    0.08    0.07      0
Doc6    0.41    0.39    0.06    0.06    0.06      0
Doc7    0.06    0.06    0.06    0.75    0.06      3
Doc8    0.05    0.05    0.57    0.05    0.29      2
Doc9    0.06    0.06    0.06    0.06    0.77      4

In [37]:
df_document_topic['topic'].value_counts().to_frame()

topic
3   3342
2   1891
1   1657
4   1586
0   1524

In [38]:
# topic word matrix
print(lda.components_)
# topic-word matrix
df_topic_words = pd.DataFrame(lda.components_)

# column and index
df_topic_words.columns = tfidf_model.get_feature_names()
df_topic_words.index = topic_names

df_topic_words.head()

[[  0.20087776  59.59132546   1.9366278  ...   3.51156401   0.38610753
    0.20188367]
 [  0.20132826   0.20049325   2.65783138 ...   0.20239222   0.20106425
    0.20119412]
 [  0.20748848   0.78846628   0.2050834  ...   1.53414392  76.44024485
    1.48364094]
 [ 30.00036313   1.11623363  41.65635907 ...  60.97577041  24.98144364
  132.19337114]
 [ 10.74207465   0.20333462   7.36798034 ...   9.06870199  92.95986846
    1.26172758]]


abl    absolut      accur  ...      worth      wrist        year
Topic0   0.200878  59.591325   1.936628  ...   3.511564   0.386108    0.201884
Topic1   0.201328   0.200493   2.657831  ...   0.202392   0.201064    0.201194
Topic2   0.207488   0.788466   0.205083  ...   1.534144  76.440245    1.483641
Topic3  30.000363   1.116234  41.656359  ...  60.975770  24.981444  132.193371
Topic4  10.742075   0.203335   7.367980  ...   9.068702  92.959868    1.261728

[5 rows x 222 columns]

In [39]:
# print top n keywords for each topic
def print_topic_words(tfidf_model, lda_model, n_words):
    words = np.array(tfidf_model.get_feature_names())
    topic_words = []
    # for each topic, we have words weight
    for topic_words_weights in lda_model.components_:
        top_words = topic_words_weights.argsort()[::-1][:n_words]
        topic_words.append(words.take(top_words))
    return topic_words

topic_keywords = print_topic_words(tfidf_model=tfidf_model, lda_model=lda, n_words=15)        

df_topic_words = pd.DataFrame(topic_keywords)
df_topic_words.columns = ['Word '+str(i) for i in range(df_topic_words.shape[1])]
df_topic_words.index = ['Topic '+str(i) for i in range(df_topic_words.shape[0])]
df_topic_words

Word 0   Word 1   Word 2   Word 3  ... Word 11 Word 12   Word 13  Word 14
Topic 0   love     gift  husband     amaz  ...     son    wear  daughter      got
Topic 1   good    great    excel  product  ...    valu    fast      work     eleg
Topic 2   like     look   awesom    thank  ...    cute   great      larg   realli
Topic 3   time     work      day      use  ...   month    cool       set     band
Topic 4   nice  perfect     band      fit  ...     pin   remov      like  leather

[5 rows x 15 columns]